### ISSUE TITLE
Formatting Issue

### ISSUE THREAD

**Issue by ByZeAman28** [vobyjs/voby#10]
I have seen Voby in Reddit (https://www.reddit.com/r/javascript/comments/ukhv0w/voby_a_new_frontend_framework_with_high/) & I am trying to see the code to create a binding library to Urql GraphQL Client (https://formidable.com/open-source/urql/), but the code is not readable enough because of the formatting & there are no comments that vscode can use to give documentation.

Could You Format the code & add comment documentations?

**Comment by fabiospampinato** [comment]
Hey, feel free to join the Discord and ping me for any clarifications or questions in general https://discord.gg/E6pK7VpnjC

> Could You Format the code

I consider the code to be already formatted, it's just an unconventional formatting which won't be changed.

> add comment documentations?

I suppose some comments could be added, I think you are referring to JSDoc-style comments, I've opened a dedicated issue for that: https://github.com/vobyjs/voby/issues/12

In general though the code IMO serves 2 purposes, be easy to work with for whoever is making the commits, and be performant/correct for whoever is executing it. Code is not meant to be easily understood by potential outside contributors, some standalone dedicated documentation should be written for that, I've opened an issue to keep track of that (since the current readme is not really proper documentation): https://github.com/vobyjs/voby/issues/11

**Comment by fabiospampinato** [comment]
As a quick shortcut this framework should work similarly to Solid, so you can largely check out their documentation and their Urql bindings to learn more about how the framework works and how the bindings should be done.

**Comment by ByZeAman28** [comment]
So you are telling me that you can't correct format the code, I have to learn solid.js. These is inconvenient & the CLI is formatted correctly but Voby & Oby are not, what up with the formatting in voby-js org?

**Comment by fabiospampinato** [comment]
> So you are telling me that you can't correctly format the code, I have to learn solid.js

No, I'm telling you that the code is correctly formatted already as far as I'm concerned, and since this is an early project it is unfortunately basically not documented, and since Solid is a similar framework you could in part use their documentation to learn how to use Voby.

> what up with the formatting in voby-js org?

The lead maintainer of each repo writes the code however they like, I'm maintaining the core stuff, I'm picking the formatting that I like. For better or for worse I can't just flip a switch and like Prettier's formatting all of a sudden.

**Comment by ByZeAman28** [comment]
Please think about it. No One would like to use unformated & ugly code. To me I always use prettier & prettier is my first party vscode plugin. Thanks.

**Comment by fabiospampinato** [comment]
I understand, but I've given this a fair bit of thought already, I'm not going to switch to Prettier.
